sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 0aZwquk/jB7kdpve8Kb3REKOErYPxU/LUxYX3LOgoYa/7hMj9hgsCyQ1737TV+IedNrrqSRC5IGppTU+Mqe9JDcRvRI2/aDvEYyqCpjsqvJxyJBNcxJory+xUzm1WcpsLlsDWRzhxZ7gMimvIdIvyn1alNLhE/b0nRyMNd6w42orW/qGuK9RQDpCJPrdeM/E0GnlwpUr/Xd+7QzOCpkWHDSHAlcewotbjiPQvLJA8fX1X80MK0Lyz16PUfc0fMroDd64qqwU3Oj9Fg8aUJ6tA7PqxpohT6CdzHRoyqIIUyAsNh5j74KcGMeTtyqS+aUK4B8QriuZdI5w1s7Xtyb8fKsltBPnG1lIz0Uo9x/ZdxtgUXzFvvBcc16LXAUlk3YH8vITBtRTVEfwUO3tKYuVk3mtFrnoXE7e2iGb+UtYiCz/Qv7vuhqo8z37QShNmxPcv2R15i/YF/8Qf0n1RWnUJ21noz5Z/r9UKS6Qgl2hHc+9O4rhyVJf9oMzpnX+ZTwJrPTJUITZF6SMCZWk8V5FduV83lkTu5sDjXoH+fLC8ze1yqmZmoudGepa2zRddq98mpPW3v6+A4PiDhoIyHvMdZjbq9vceMNrg0feQJjbPExe6o6bgyykzRvSleWzw9bms7QzpW19TxcImX7zEQRf5Umjm3IwzYYC6bBIC+EbblE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Man-of-Destiny_4024
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy